#############################################################################
# Generated by PAGE version 7.1
#  in conjunction with Tcl version 8.6
#  Feb 16, 2022 09:52:09 PM CET  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1078x688+239+0
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(complement_color)]
    ttk::notebook $top.tNo46 \
        -width 1022 -height 316 -takefocus {} 
    vTcl:DefineAlias "$top.tNo46" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo46.t0 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo46.t0" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo46 add $top.tNo46.t0 \
        -padding 0 -sticky nsew -state normal -text {CSV Load} -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo46.t0
    entry $site_4_0.ent46 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black -width 10 
    vTcl:DefineAlias "$site_4_0.ent46" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab47 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -text Filename: 
    vTcl:DefineAlias "$site_4_0.lab47" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but48 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text ... 
    vTcl:DefineAlias "$site_4_0.but48" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab49 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -text Delimeter: 
    vTcl:DefineAlias "$site_4_0.lab49" "Label2" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_0.tCo50 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo50" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab51 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -text Coma: 
    vTcl:DefineAlias "$site_4_0.lab51" "Label3" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_0.tCo52 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo52" "TCombobox2" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_0.scr53 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 271 -highlightcolor black -width 602 
    vTcl:DefineAlias "$site_4_0.scr53" "Scrolledtext2" vTcl:WidgetProc "Toplevel1" 1

    $site_4_0.scr53.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground blue \
        -selectforeground white \
        -width 10 \
        -wrap none
    label $site_4_0.lab54 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -text Header: 
    vTcl:DefineAlias "$site_4_0.lab54" "Label4" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_0.tCo56 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo56" "TCombobox3" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.ent46 \
        -in $site_4_0 -x 0 -relx 0.133 -y 0 -rely 0.069 -width 186 \
        -relwidth 0 -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab47 \
        -in $site_4_0 -x 0 -relx 0.02 -y 0 -rely 0.069 -width 0 \
        -relwidth 0.077 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but48 \
        -in $site_4_0 -x 0 -relx 0.333 -y 0 -rely 0.069 -width 43 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab49 \
        -in $site_4_0 -x 0 -relx 0.02 -y 0 -rely 0.241 -width 0 \
        -relwidth 0.087 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tCo50 \
        -in $site_4_0 -x 0 -relx 0.137 -y 0 -rely 0.241 -width 0 \
        -relwidth 0.125 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab51 \
        -in $site_4_0 -x 0 -relx 0.02 -y 0 -rely 0.414 -width 0 \
        -relwidth 0.061 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tCo52 \
        -in $site_4_0 -x 0 -relx 0.137 -y 0 -rely 0.414 -width 0 \
        -relwidth 0.174 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_0.scr53 \
        -in $site_4_0 -x 0 -relx 0.402 -y 0 -rely 0.034 -width 0 \
        -relwidth 0.59 -height 0 -relheight 0.934 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab54 \
        -in $site_4_0 -x 0 -relx 0.02 -y 0 -rely 0.586 -width 0 \
        -relwidth 0.068 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tCo56 \
        -in $site_4_0 -x 0 -relx 0.137 -y 0 -rely 0.572 -width 0 \
        -relwidth 0.075 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    frame $top.tNo46.t1 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo46.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo46 add $top.tNo46.t1 \
        -padding 0 -sticky nsew -state normal -text {Format columns} \
        -image {} -compound left -underline -1 
    set site_4_1  $top.tNo46.t1
    label $site_4_1.lab70 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -text Column: 
    vTcl:DefineAlias "$site_4_1.lab70" "Label10" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_1.tCo71 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_1.tCo71" "TCombobox9" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_1.lab72 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -text {Current Format:} 
    vTcl:DefineAlias "$site_4_1.lab72" "Label11" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_1.lab73 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -text Format 
    vTcl:DefineAlias "$site_4_1.lab73" "Label12" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_1.lab74 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -text {choose new Format:} 
    vTcl:DefineAlias "$site_4_1.lab74" "Label13" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_1.tCo75 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_1.tCo75" "TCombobox10" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_1.but76 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {set new format} 
    vTcl:DefineAlias "$site_4_1.but76" "Button4" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_1.lab70 \
        -in $site_4_1 -x 0 -relx 0.02 -y 0 -rely 0.034 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tCo71 \
        -in $site_4_1 -x 0 -relx 0.175 -y 0 -rely 0.034 -width 0 \
        -relwidth 0.175 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_1.lab72 \
        -in $site_4_1 -x 0 -relx 0.02 -y 0 -rely 0.138 -width 0 \
        -relwidth 0.112 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_1.lab73 \
        -in $site_4_1 -x 0 -relx 0.175 -y 0 -rely 0.138 -width 0 \
        -relwidth 0.175 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_1.lab74 \
        -in $site_4_1 -x 0 -relx 0.02 -y 0 -rely 0.241 -width 0 \
        -relwidth 0.136 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tCo75 \
        -in $site_4_1 -x 0 -relx 0.175 -y 0 -rely 0.241 -width 0 \
        -relwidth 0.174 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_1.but76 \
        -in $site_4_1 -x 0 -relx 0.02 -y 0 -rely 0.345 -width 123 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo46.t3 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo46.t3" "TNotebook1_t3" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo46 add $top.tNo46.t3 \
        -padding 0 -sticky nsew -state normal -text Statistics -image {} \
        -compound left -underline -1 
    set site_4_2  $top.tNo46.t3
    label $site_4_2.lab58 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -text {Y Value Column:} 
    vTcl:DefineAlias "$site_4_2.lab58" "Label5" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_2.tCo59 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_2.tCo59" "TCombobox4" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_2.lab60 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -text {Group Column:} 
    vTcl:DefineAlias "$site_4_2.lab60" "Label6" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_2.tCo61 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_2.tCo61" "TCombobox5" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_2.lab62 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -text {Group Column:} 
    vTcl:DefineAlias "$site_4_2.lab62" "Label7" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_2.tCo63 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_2.tCo63" "TCombobox6" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_2.lab64 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -text Diagram: 
    vTcl:DefineAlias "$site_4_2.lab64" "Label8" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_2.tCo65 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_2.tCo65" "TCombobox7" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_2.lab66 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -text {X Value Column:} 
    vTcl:DefineAlias "$site_4_2.lab66" "Label9" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_2.tCo67 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_2.tCo67" "TCombobox8" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_2.but68 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Plot 
    vTcl:DefineAlias "$site_4_2.but68" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_2.but69 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {General Statitics} 
    vTcl:DefineAlias "$site_4_2.but69" "Button3" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_2.lab58 \
        -in $site_4_2 -x 0 -relx 0.02 -y 0 -rely 0.034 -width 0 \
        -relwidth 0.109 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_2.tCo59 \
        -in $site_4_2 -x 0 -relx 0.131 -y 0 -rely 0.034 -width 0 \
        -relwidth 0.175 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_2.lab60 \
        -in $site_4_2 -x 0 -relx 0.02 -y 0 -rely 0.172 -width 0 \
        -relwidth 0.098 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_2.tCo61 \
        -in $site_4_2 -x 0 -relx 0.131 -y 0 -rely 0.169 -width 0 \
        -relwidth 0.175 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_2.lab62 \
        -in $site_4_2 -x 0 -relx 0.02 -y 0 -rely 0.31 -width 0 \
        -relwidth 0.107 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_2.tCo63 \
        -in $site_4_2 -x 0 -relx 0.131 -y 0 -rely 0.3 -width 0 \
        -relwidth 0.174 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_2.lab64 \
        -in $site_4_2 -x 0 -relx 0.02 -y 0 -rely 0.448 -width 0 \
        -relwidth 0.077 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_2.tCo65 \
        -in $site_4_2 -x 0 -relx 0.13 -y 0 -rely 0.434 -width 0 \
        -relwidth 0.175 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_2.lab66 \
        -in $site_4_2 -x 0 -relx 0.333 -y 0 -rely 0.034 -width 0 \
        -relwidth 0.116 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_2.tCo67 \
        -in $site_4_2 -x 0 -relx 0.451 -y 0 -rely 0.034 -width 0 \
        -relwidth 0.174 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_4_2.but68 \
        -in $site_4_2 -x 0 -relx 0.504 -y 0 -rely 0.383 -width 113 \
        -relwidth 0 -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but69 \
        -in $site_4_2 -x 0 -relx 0.02 -y 0 -rely 0.793 -width 153 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo46.t4 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo46.t4" "TNotebook1_t4" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo46 add $top.tNo46.t4 \
        -padding 0 -sticky nsew -state normal -text Info -image {} \
        -compound left -underline -1 
    set site_4_3  $top.tNo46.t4
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_3.scr57 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 261 -highlightcolor black -width 992 
    vTcl:DefineAlias "$site_4_3.scr57" "Scrolledtext3" vTcl:WidgetProc "Toplevel1" 1

    $site_4_3.scr57.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground blue \
        -selectforeground white \
        -width 10 \
        -wrap none
    place $site_4_3.scr57 \
        -in $site_4_3 -x 0 -relx 0.02 -y 0 -rely 0.034 -width 0 \
        -relwidth 0.975 -height 0 -relheight 0.934 -anchor nw \
        -bordermode ignore 
    vTcl::widgets::ttk::scrolledtext::CreateCmd $top.scr47 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr47" "Scrolledtext1" vTcl:WidgetProc "Toplevel1" 1

    $top.scr47.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground blue \
        -selectforeground white \
        -width 10 \
        -wrap none
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo46 \
        -in $top -x 0 -relx 0.019 -y 0 -rely 0.015 -width 0 -relwidth 0.948 \
        -height 0 -relheight 0.459 -anchor nw -bordermode ignore 
    place $top.scr47 \
        -in $top -x 0 -relx 0.019 -y 0 -rely 0.494 -width 0 -relwidth 0.957 \
        -height 0 -relheight 0.467 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

